# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.0.3

        environment:
          AWS_REGION: eu-west-1
          AWS_DEFAULT_REGION: eu-west-1
          AWS_SSH_USERNAME: ubuntu
          AWS_SOURCE_AMI: ami-c8b51fb1
          AWS_INTANCE_TYPE: c4.large
          AWS_SPOT_PRICE: 0.03
          KUBERNETES_VERSION: 1.9.5
          KUBERNETES_RELEASE_TAG: v1.9.5
          ETCD_RELEASE_TAG: 3.1.11
          K8S_DNS_RELEASE_TAG: 1.14.7
          HELM_RELEASE_TAG: v2.8.2
          PROMETHEUS_RELEASE_TAG: v2.1.0
          BASE_NAME: pipeline-cp-image
    steps:
      - checkout

      - run:
          name: Build Packer
          no_output_timeout: 2700
          command: |
            GIT_REV=$(git rev-parse --short HEAD)
            GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            export AWS_IMAGE_NAME=$BASE_NAME-$GIT_BRANCH-$GIT_REV-$(date +%y%m%d%H%M)
            packer build ./packer.json